name: Robot tests

on: [push, pull_request]

jobs:
  integrationtest:
    runs-on: ubuntu-latest
    container: python:3.9
    strategy:
      fail-fast: false
      matrix:
        auth_enabled: ['false']      
        camunda_version: ['run-7.16.0']
    services:
      camunda:
        image: camunda/camunda-bpm-platform:${{ matrix.camunda_version }}
        ports:
          - 8080:8080
        env:
          camunda.bpm.run.auth.enabled: ${{ matrix.auth_enabled }}
    steps:
    - uses: actions/checkout@v2
    - name: Test with robot
      env:
        CAMUNDA_HOST: http://camunda:8080
      run: |
        pip install -r requirements.txt
        sleep 20
        robot --nostatusrc -d logs -b debug-prepare-20.log -x xunit-prepare-20.xml -o output-prepare-20.xml -r repot-prepare-20.html -l log-prepare-20.html -L DEBUG tests/20_get_coffee_ingredients/prepare.robot
        robot --nostatusrc -d logs -b debug-task-20.log -x xunit-task-20.xml -o output-task-20.xml -r repot-task-20.html -l log-task-20.html -L DEBUG tasks/20_get_coffee_ingredients/task.robot
        robot --nostatusrc -d logs -b debug-validate-20.log -x xunit-validate-20.xml -o output-validate-20.xml -r repot-validate-20.html -l log-validate-20.html -L DEBUG tests/20_get_coffee_ingredients/validate.robot

        robot --nostatusrc -d logs -b debug-prepare-30.log -x xunit-prepare-30.xml -o output-prepare-30.xml -r repot-prepare-30.html -l log-prepare-30.html -L DEBUG tests/30_prepare_coffee/prepare.robot
        robot --nostatusrc -d logs -b debug-task-30.log -x xunit-task-30.xml -o output-task-30.xml -r repot-task-20.html -l log-task-20.html -L DEBUG tasks/30_prepare_coffee/task.robot
        robot --nostatusrc -d logs -b debug-validate-30.log -x xunit-validate-30.xml -o output-validate-30.xml -r repot-validate-20.html -l log-validate-20.html -L DEBUG tests/30_prepare_coffee/validate.robot

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: robot logs
        path: |
          logs/
  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: integrationtest
    runs-on: ubuntu-latest
    # the build-and-test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
           name: robot logs

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: xunit*.xml