name: Robot tests

on: [push, pull_request]

jobs:
  integrationtest:
    runs-on: ubuntu-latest
    container: python:3.9
    strategy:
      fail-fast: false
      matrix:
        auth_enabled: ['false']      
        camunda_version: ['run-7.16.0']
    services:
      camunda:
        image: camunda/camunda-bpm-platform:${{ matrix.camunda_version }}
        ports:
          - 8080:8080
        env:
          camunda.bpm.run.auth.enabled: ${{ matrix.auth_enabled }}
    steps:
    - uses: actions/checkout@v2
    - name: Test with robot
      env:
        CAMUNDA_HOST: http://camunda:8080
      run: |
        pip install -r requirements.txt
        sleep 20
        robot --nostatusrc -d logs-20 -b debug-prepare.log -o output-prepare.xml -L DEBUG tests/20_get_coffee_ingredients/prepare.robot
        robot --nostatusrc -d logs-20 -b debug-task.log -o output-task.xml -L DEBUG tasks/20_get_coffee_ingredients/task.robot
        robot --nostatusrc -d logs-20 -b debug-validate.log -o output-validate.xml -L DEBUG tests/20_get_coffee_ingredients/validate.robot
        rebot --nostatusrc -d logs-20-all -N Regressiontests -o output-tests.xml -R logs-20/output-prepare.xml logs-20/output-validate.xml 

        robot --nostatusrc -d logs-30 -b debug-prepare.log -o output-prepare.xml -L DEBUG tests/30_prepare_coffee/prepare.robot
        robot --nostatusrc -d logs-30 -b debug-task.log -o output-task.xml -L DEBUG tasks/30_prepare_coffee/task.robot
        robot --nostatusrc -d logs-30 -b debug-validate.log -o output-validate.xml -L DEBUG tests/30_prepare_coffee/validate.robot
        rebot --nostatusrc -d logs-30-all -N Regressiontests -o output-tests.xml -R logs-30/output-prepare.xml logs-30/output-validate.xml 

        rebot --nostatusrc -d logs -o output-tasks.xml -x xunit-tasks.xml -r report-tasks.html -l log-tasks.html -R logs-20/output-task.xml logs-30/output-task.xml
        rebot -d logs -o output-tests.xml -x xunit-tests.xml -r report-tests.html -l log-tests.html -R logs-30-all/output-tests.xml logs-20-all/output-tests.xml 
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: robot logs
        path: |
          logs/
  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: integrationtest
    runs-on: ubuntu-latest
    # the build-and-test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
           name: robot logs

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: xunit*.xml